using System;

/// <summary>
/// *********************************************************************************************************************
/// Copyright©: 	2015 YourJester Company. All rights reserved.
/// *********************************************************************************************************************
/// Creation:	    June 2015
/// Author:	    	Rosemeire Deconti
/// Goal:           Return a confirmation code to user LogOn the portal (generated by random routine)
/// *********************************************************************************************************************
/// Maintenance:    dd/mm/yyyy
/// Author:	    	name
/// Goal:           inform the description of maintenance
/// *********************************************************************************************************************
/// </summary>

namespace YourJester.AppLogic
{
    public class R0170TreatCodeConfirmation
    {
        public string Routine0170TreatCodeConfirmation()
        {
            Random rndNumero = new Random();
            string userConfirmation = rndNumero.Next().ToString();
            return userConfirmation;
        }
    }
}